### ISSUE TITLE
Mid-term Project Assets

### ISSUE THREAD

**Issue by ogun0054** [ogun0054/mtm6201-midterm#1]
Dear Professors,

I hope you are enjoying your mid-term break and finding it productive. I am writing to inquire about the assets required for our project. I have reviewed the instructions but could not find any links to the assets. Could you please provide guidance on how to access them? I would like to continue working on the project as soon as possible.

Thank you for your time and support.

Best regards,
Ismail A. Ogundele(ogun0054)

@wendywarren

**Comment by wendywarren** [comment]
Hi @ogun0054 

The assets are never available from the summary of the assignments within the weekly modules. To access the assets and rubric, you have to click thru to the assignment.

Scroll down the page past the screenshots and in that last section you will see a zip folder with the assets.

Here's a screenshot to better guide you:

<img width="1597" alt="Screen Shot 2024-06-26 at 12 04 31 PM" src="https://github.com/ogun0054/mtm6201-midterm/assets/12865609/1dd04f8c-26fc-4ceb-9576-938bdb812318">


Thanks and good luck!
Wendy

**Comment by ogun0054** [comment]
@wendywarren 

Thank you for your support. I have now been able to access the assets. I am very grateful.
